lexik_jwt_authentication:
    private_key_path: "%kernel.project_dir%/var/jwt/private.pem"
    public_key_path:  "%kernel.project_dir%/var/jwt/public.pem"
    pass_phrase:      '%env(JWT_KEY_PASSPHRASE)%'
    token_ttl:        3600
