#index:
#    path: /
#    controller: App\Controller\WelcomeController::list

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
